### ISSUE TITLE
Rename to "InputfieldRepeaterMatrixDuplicate"

### ISSUE THREAD

**Issue by MrSnoozles** [FlipZoomMedia/InputfieldRepeaterMatrixDublicate#1]
Hey David,

great module, super useful when working with repeater matrixes. I was just wondering, is the spelling "dublicate" on purpose or rather a misspelling of "duplicate"?

Keep up the great work!
MrSnoozles

**Comment by flipzoom** [comment]
You're absolutely right. Stupid typo. But at least consistently everywhere. :-) I will change it in the next update round. 👍

**Comment by flipzoom** [comment]
Fixed in version 1.0.4.
